plugins {
    id 'java'
    id 'org.jetbrains.intellij' version '1.17.3'
}

group 'com.chu7'
version '1.0.0'

repositories {
    mavenCentral()
}

intellij {
    version = '2023.1'
    type = 'IU' //旗舰版
}

patchPluginXml {
    changeNotes = """
      初始版本
    """
}
tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}
tasks.withType(JavaExec) {
    jvmArgs '-Dfile.encoding=UTF-8'
}
dependencies {
    // 你的依赖
}