plugins {
    id 'java'
    id 'org.jetbrains.intellij' version '1.17.3'
}

group 'com.chu7'
version '1.0.1'

repositories {
    mavenCentral()
}

intellij {
    version = '2024.1'
    type = 'IU' //旗舰版
}

patchPluginXml {
    changeNotes = """
      初始版本
    """
}
tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}
tasks.withType(JavaExec) {
    jvmArgs '-Dfile.encoding=UTF-8'
}

tasks {
    patchPluginXml {
        sinceBuild.set("241")
        untilBuild.set("252.*")

    }

    signPlugin {
        // 可选：如果你已有证书可在这里配置，否则用 JetBrains Console 上传时签名
//        certificateChain.set(file("certs/chain.crt").readText())
//        privateKey.set(file("certs/private.pem").readText())
//        password.set("your-password")
    }

    publishPlugin {
        token.set(System.getenv("PUBLISH_TOKEN")) // 建议使用环境变量
    }
}
dependencies {
    // Gson for JSON parsing
    implementation 'com.google.code.gson:gson:2.10.1'
}